---
title: "在线课程-网络数据结构Task7"
author: "杜兴兴"
date: "2021/3/26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 准备工作

```{r message=FALSE, warning=FALSE}
# 清除工作环境
rm(list = ls())
# 加载必要包
library(igraph)  
library(dplyr)
library(plyr)
library(ggplot2)
```


## 任务一: 读入数据并构建网络 
```{r message=FALSE, warning=FALSE}
data = read.csv("../A2_data/edge_core.csv") 
# head(data)
g <- graph_from_data_frame(data,directed = F)
print(paste("网络的节点数为：",length(V(g))))
print(paste("网络的边数为：",length(E(g))))
print(paste("网络的密度为：",graph.density(g)))

```

## 任务二: 度分布直方图
```{r message=FALSE, warning=FALSE}
deg <- degree(g)
length(deg)
hist(deg,xlab = "度",ylab = "频数",main="",col = "white")
```

通过观察上面直方图可以发现，节点的分布基本呈现右偏，大部分节点的度都在0-20范围内，节点度大于20的只有极少数。

## 任务三：节点度


```{r}
head(df.deg[order(df.deg$deg,dedecreasing = T),])
df.deg[order(df.deg$deg,decreasing = T),]

data <- ddply(data,.(node1),nrow)   
data[order(data$V1,decreasing = T),]

data[!duplicated(data$node1),]
names(deg)
xxx<- (c(names(deg),data[!duplicated(data$node1),1]))
length(xxx)
length(xxx[!duplicated(xxx)])
id <- names(deg) %in% data[!duplicated(data$node1),1]
length(xxx[!id])
length(deg)-length(data[!duplicated(data$node1),1])
```

```{r message=FALSE, warning=FALSE}
df.deg <- as.data.frame(deg)
df.deg$name <- rownames(df.deg)

author <- read.csv("../A2_data/author.csv") 

author.deg <- merge(author,df.deg,by = "name")
author.deg <- author.deg[order(author.deg$deg,decreasing = T),c(3,1,2)]
rownames(author.deg) <- 1:nrow(author.deg)
head(author.deg,n = 10)





```

可以从上面结果可以看出，合作最多的作者为Carroll, R共有76人与其合作，且明显多于其它作者；其次是Ibrahim, J和Zeng, D分别有42、40人合作。另外可以看到前10名中的合作人数都是大于20人。

## 任务四：中介中心性

```{r message=FALSE, warning=FALSE}
bet <- betweenness(g,normalized = T)
df.bet <- as.data.frame(bet)
df.bet$name <- rownames(df.bet)
author.bet <- merge(df.bet,author,by = 'name')
author.bet <- author.bet[order(author.bet$bet,decreasing = T),c(2,1,3)]
rownames(author.bet) <- 1:nrow(author.bet)
head(author.bet,10)

```

可以从上面结果可以看出，中介中心性最高的作者为Carroll, R达到0.21，且明显高于其它作者，说明该作者在该领域的影响力和重要性很高；其次是	Lin, X和Hall, P。

## 任务五：网络社区发现
```{r message=FALSE, warning=FALSE}
comm <- multilevel.community(g)
len <- lengths(comm,use.names = F)
names(len) <- 1:length(len)
len
```

## 任务六：网络可视化

```{r message=FALSE, warning=FALSE}
comm <- multilevel.community(g) # 社区发现
nodes <- V(g)[comm$membership == 39]  # 提取社区节点

g.sub <- induced_subgraph(g,nodes)   # 选择子网络
name <- names(which.max(degree(g.sub)))  
maxlabel <- author[which(author$name == name),"author"]  # 匹配最大度的标签姓名

V(g.sub)$label = ""
V(g.sub)[max(degree(g.sub))]$label = maxlabel   # 设置标签
V(g.sub)[sort(degree(g.sub),decreasing = T)[1]]$label = maxlabel   # 设置标签

plot(g.sub,   # 绘图
     vertex.size = degree(g.sub)*0.5,vertex.color = "cyan" ,
     vertex.label.dist=0.05,
     layout = layout.fruchterman.reingold)

print(paste("子网络的密度为：",graph.density(g)))
```









